controller:
  hostNetwork: false
  hostPort:
    enabled: false
    ports:
      http: 80
      https: 443
  service:
    type: LoadBalancer
  publishService:
    enabled: true
  ingressClassResource:
    enabled: true
    name: nginx
  watchIngressWithoutClass: false
