export const SUBTITLE_LANGUAGES = {
    en: 'English',
    es: 'Spanish',
    fr: 'French',
    de: 'German',
    it: 'Italian',
    pt: 'Portuguese',
    pl: 'Polish',
    hi: 'Hindi',
    ja: 'Japanese',
    ko: 'Korean',
    zh: 'Chinese',
    ar: 'Arabic',
    ru: 'Russian',
    tr: 'Turkish',
    nl: 'Dutch',
    sv: 'Swedish',
    id: 'Indonesian',
    vi: 'Vietnamese',
    th: 'Thai',
    uk: 'Ukrainian',
    el: 'Greek',
};
